"""add parsed_text to resume

Revision ID: bb7eded77c5f
Revises: f3a5d73bf63b
Create Date: 2026-07-21 12:33:04.176359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb7eded77c5f'
down_revision: Union[str, Sequence[str], None] = 'f3a5d73bf63b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('parsed_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'parsed_text')
    # ### end Alembic commands ###
