"""
Centralized Modular Prompt Engineering Service for CampusIQ.

Constructs modular system and user prompts, handles conversation memory injection,
and enforces strict grounding, citation rules, and hallucination prevention.
"""

import logging
from typing import Any, Dict, List, Optional

from app.services.ai.chunker import count_tokens

# Set up module logger
logger = logging.getLogger(__name__)

# System Identity & Persona
SYSTEM_IDENTITY = """You are CampusIQ, an expert academic AI study assistant for university students."""

# Core Behavior & Grounding Rules
GROUNDING_RULES = """Strict Behavioral Rules:
1. Grounding & Factuality: Answer strictly using ONLY the provided Study Material Context. Never hallucinate or introduce outside facts.
2. Insufficient Context: If the provided context does not contain enough information to answer accurately, explicitly state: "I couldn't find relevant information in the uploaded study material."
3. Formatting: Be concise, clear, and direct. Use structured bullet points and subheadings for complex explanations.
4. Code & Math Integrity: Preserve all mathematical notation (LaTeX/equations) and code blocks exactly as given in the context.
5. Accurate Citations: Never fabricate or invent page numbers, document IDs, or section headings.
6. Inferences: If an answer requires logical inference from the context, explicitly mention that the statement is inferred from the provided material."""

# Formatting Guidelines
FORMATTING_GUIDELINES = """Response Style:
- Professional, supportive, and academically rigorous.
- Clear structural hierarchy (Markdown headers, bold concepts, bullet lists).
- Keep explanations clear and focused."""


def build_system_prompt(custom_instructions: Optional[str] = None) -> str:
    """
    Construct the complete system prompt for CampusIQ AI Assistant.

    Args:
        custom_instructions: Optional additional domain directives.

    Returns:
        Formatted system prompt string.
    """
    logger.debug("Building modular system prompt.")
    prompt_parts = [SYSTEM_IDENTITY, GROUNDING_RULES, FORMATTING_GUIDELINES]

    if custom_instructions and custom_instructions.strip():
        prompt_parts.append(f"Additional Directives:\n{custom_instructions.strip()}")

    return "\n\n".join(prompt_parts)


def build_user_prompt(
    question: str,
    context: str,
    chat_history: Optional[List[Dict[str, str]]] = None,
    max_history_messages: int = 6,
) -> str:
    """
    Format user question, retrieved document context, and optional conversation history.

    Args:
        question: Current user question string.
        context: Formatted context string generated by retriever.py.
        chat_history: Optional list of past chat messages [{"role": "user"|"assistant", "content": "..."}].
        max_history_messages: Maximum number of recent history messages to include (default 6).

    Returns:
        Formatted user prompt for LLM consumption.

    Raises:
        ValueError: If question is empty or invalid.
    """
    if not isinstance(question, str) or not question.strip():
        logger.error("Invalid question passed to build_user_prompt: %r", question)
        raise ValueError("Question must be a non-empty string.")

    clean_question = question.strip()
    clean_context = (context or "").strip() or "[NO CONTEXT RETRIEVED]"

    # Format conversation history if provided
    history_str = ""
    if chat_history:
        recent_history = chat_history[-max_history_messages:]
        history_lines = []
        for msg in recent_history:
            role = msg.get("role", "user").capitalize()
            content = msg.get("content", "").strip()
            if content:
                history_lines.append(f"{role}: {content}")
        if history_lines:
            history_str = "Recent Conversation History:\n" + "\n".join(history_lines) + "\n\n"

    user_prompt = f"""Study Material Context:
--------------------------------------------------
{clean_context}
--------------------------------------------------

{history_str}User Question:
{clean_question}

Instructions:
- Answer the User Question using ONLY the Study Material Context above.
- If conversation history is present, use it for context regarding follow-up references.
- If the study material does not contain the answer, state that information is insufficient.
"""
    return user_prompt


def estimate_prompt_tokens(system_prompt: str, user_prompt: str) -> int:
    """
    Estimate total tokens for the combined system and user prompt.

    Args:
        system_prompt: System prompt string.
        user_prompt: User prompt string.

    Returns:
        Total estimated token count integer.
    """
    combined_text = f"{system_prompt}\n\n{user_prompt}"
    return count_tokens(combined_text)
